/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package password;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author johna
 */
public class firstPage extends javax.swing.JFrame {

    /**
     * Creates new form firstPage
     */
    public firstPage() {
        initComponents();
    }
    String fname, lname, mname, firstup, lastup, flow, llow, midup, num, num1, loc,u,p;
    int space, space1, space2;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ml = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        mnTF = new javax.swing.JTextField();
        lnTF = new javax.swing.JTextField();
        fnTF = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        phonenumber = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        uTF = new javax.swing.JTextField();
        pnTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pTF = new javax.swing.JTextField();
        locTF2 = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ml.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ml.setText("Middle Name");
        getContentPane().add(ml, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 20));

        ln.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ln.setText("Last Name");
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 80, 20));

        fn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        fn.setText("First Name");
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 20));
        getContentPane().add(mnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 130, -1));
        getContentPane().add(lnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 130, -1));

        fnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnTFActionPerformed(evt);
            }
        });
        getContentPane().add(fnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, -1));

        btn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password/CONFIRM (1).gif"))); // NOI18N
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 120, 20));

        phonenumber.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        phonenumber.setText("Phone Number");
        getContentPane().add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 90, 20));

        location.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        location.setText("Location");
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 90, 20));

        uTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uTFActionPerformed(evt);
            }
        });
        getContentPane().add(uTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 80, -1));

        pnTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnTFActionPerformed(evt);
            }
        });
        getContentPane().add(pnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 130, -1));

        jLabel1.setText("pass");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLabel2.setText("user");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));
        getContentPane().add(pTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 80, -1));
        getContentPane().add(locTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 130, -1));

        bg.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password/Untitled design (1).gif"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:   
        secondPage sp = new secondPage();
        
        //BUTTON

        fname = fnTF.getText();
        mname = mnTF.getText();
        lname = lnTF.getText();

        //FIRSTNAME
        if(fname.matches("^[a-z A-Z]+$")){
            fname = fname.trim();
            firstup = fname.toUpperCase();
            flow = fname.toLowerCase();
            space = fname.indexOf(" ");

            if(fname.indexOf(" ") == -1){
                fname = firstup.charAt(0)+flow.substring(1);
            }
            else{
                fname = firstup.charAt(0)+flow.substring(1, space)+" "+firstup.charAt(space+1)+flow.substring(space+2);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "PLEASE ENTER LETTERS ONLY");
        }

        //MIDDLE NAME
        if(mname.matches("^[a-z A-Z]+$")){
            mname = mname.trim();
            midup = mname.toUpperCase();
            space2 = mname.indexOf(" ");
            if(mname.indexOf(" ") == -1){
                mname = midup.substring(0,1);
            }

            else{
                mname = midup.substring(0,1)+"."+midup.charAt(space2+1);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "PLEASE ENTER LETTERS ONLY");
        }

        //LASTNAME
        if(lname.matches("^[a-z A-Z]+$")){
            lname = lname.trim();
            lastup = lname.toUpperCase();
            llow = lname.toLowerCase();
            space1 = lname.indexOf(" ");
            if(lname.indexOf(" ") == -1){
                lname = lastup.charAt(0)+llow.substring(1);
            }
            else{
                lname = lastup.charAt(0)+llow.substring(1, space1)+" "+lastup.charAt(space1+1)+llow.substring(space1+2);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "PLEASE ENTER LETTERS ONLY");
        }

        
        
        loc = locTF2.getText();
        num = pnTF.getText();
        u = uTF.getText();
        p = pTF.getText();
        num1 = Integer.toString(num.length());
        if(num.matches("^[0-9]+$")){
            if(num1.equals("11")){
            // if pass the all condition
            
                
                sp.user1 = u;
                sp.pass1 = p;
                sp.username = u;
                sp.firstname = fname;
                sp.middlename = mname;
                sp.lastname = lname;
                sp.phonenumber = num;
                sp.location = loc;
                sp.show();
                dispose();
                
                
            }
            else JOptionPane.showMessageDialog(null, "PLEASE ENTER 11 DIGITS ONLY");
        }
        else JOptionPane.showMessageDialog(null, "PHONE NUMBER ERROR! DIGITS ONLY");

        
        
        


    }//GEN-LAST:event_btnActionPerformed

    private void pnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnTFActionPerformed

    private void fnTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnTFActionPerformed

    private void uTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn;
    private javax.swing.JLabel fn;
    public javax.swing.JTextField fnTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ln;
    public javax.swing.JTextField lnTF;
    public javax.swing.JTextField locTF2;
    private javax.swing.JLabel location;
    private javax.swing.JLabel ml;
    public javax.swing.JTextField mnTF;
    public javax.swing.JTextField pTF;
    private javax.swing.JLabel phonenumber;
    public javax.swing.JTextField pnTF;
    public javax.swing.JTextField uTF;
    // End of variables declaration//GEN-END:variables
}
