/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package password;

/**
 *
 * @author johna
 */
public class thirdPage extends javax.swing.JFrame {

    /**
     * Creates new form thirdPage
     */
    public thirdPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phonenumber = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        middlename = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phonenumber.setText("jLabel1");
        getContentPane().add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 160, -1));

        location.setText("jLabel1");
        getContentPane().add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 170, -1));

        firstname.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        firstname.setText("JOHNAS ");
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, 80));

        lastname.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lastname.setText("BLASCO");
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 180, 80));

        middlename.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        middlename.setText(" L ");
        getContentPane().add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 50, 80));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 50, -1));

        username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username.setText("jLabel1");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 25, 190, 40));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password/STUDENT DATABASE.gif"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        start s = new start();
        s.show();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thirdPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    public javax.swing.JLabel firstname;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lastname;
    public javax.swing.JLabel location;
    private javax.swing.JButton logout;
    public javax.swing.JLabel middlename;
    public javax.swing.JLabel phonenumber;
    public javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
